version: "3.9"
services:
  dcem:
    build: ./dcem
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
      - dcem-data:/opt/DCEM/DCEM_HOME
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dcem
      MYSQL_USER: dcem
      MYSQL_PASSWORD: changeme
volumes:
  dcem-data:
  mariadb-data:
